URLS: # links to schedules 
  "DelVal": "https://docs.google.com/spreadsheets/d/1p_TaLcSPFhKI6RB45m7Wk4mpaVYp79O0IqQ9egaMPBM"
  "Dembla": "https://docs.google.com/spreadsheets/d/1GgkuvbTPKm5yEJBPhVzhqgzCryTou3X4v35ZgTKPkcw"
  "EHO": "https://docs.google.com/spreadsheets/d/1Zu-ISFlPk4pvb0jvvUXjhkw0uXWsYWmxmkqFWOxMVHU"
  "HawaTubes": "https://docs.google.com/spreadsheets/d/1PY4LKYVw_GoPSIW9b7fITQtX0ZdpmnrYj6Pe-KmCACQ"
  "LC": "https://docs.google.com/spreadsheets/d/1OgPGNrtFdSGnQAwGs2QuvS5CSQXWpOQqI8w5y9-L-sc"
  "Nirmal": "https://docs.google.com/spreadsheets/d/12_89P4pS6nDN34o00hB7M2AQoDnUM-iGe6PtkPh0RPg"
  "RKC": "https://docs.google.com/spreadsheets/d/1Tgol6dqz9bUhei1OHv5tSATsyW2q95c5HikWo5gipWw"
  "SDTork": "https://docs.google.com/spreadsheets/d/1fk9J8N7HuBVFnKv_rS8te_6dpya3bYkaOeWM9U_y70Y"
  "Jsons": "https://docs.google.com/spreadsheets/d/1jVV7I77F8PHOWcwqESKDktfQuDFhZdYOZJlk6vs85ac"
  

SHORT_NAMES:
  "Dembla": "DL"
  "DelVal": "DV"
  "HawaTubes": "HWT"
  "LC": "LC"
  "RKC": "RKC"
  "Nirmal": "NL"
  "SDTork": "SDT"
  "Jsons": "JS"
  
POSTGRES_COLUMN_NAME_2_AIRTABLE_COLUMN_NAME:
  "dos": "Date of submission"
  "pono": "PO No."
  "pono_manuf": "PO No. - Manufacturer"
  "poitem": "PO. ITEM"
  "qty": "QTY of valves"
  "kks": "KKS_string"
  "stage": "STAGE of shift"
  "stage_ru": "STAGE of shift (RU)"
  "finish_before_shift": "BEFORE (finish date)"
  "finish_after_shift": "AFTER (finish date)"
  "delta": "Delta in duration, days"
  "duration": "Duration after shift, days"
  "greater_then_avg": "Greater then average"
  "manufacturer": "Manufacturer"
  "readiness_to_res_inspection": "READINESS to RES INSPECTION"
  "detail": "Detail"
  "sheet_name": "Sheet name"
  "fname": "Foundry name"

COLORS:
    (255, 255, 0):   "yellow"
    (255, 0, 0):     "red"
    (153, 153, 153): "gray"
    (147, 196, 125): "green"
    (52, 168, 83):   "green"
    (146, 208, 80):  "green"
    (255, 255, 255): "white"
    None: "NULL"

EXISTING_COMPONENTS: ["BODY", "BONNET", "DISC", "CAGE", "END CONNECTOR", "WNF", "SEAT", "WEDGE", "COVER"]
  