services:
  pg_res:
    image: postgres:12.6
    environment:
      POSTGRES_USER: resdb
      POSTGRES_PASSWORD: resdb
      POSTGRES_DB: resdb
    volumes:
      - resdb_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "3334:5432"
    networks:
      - airflow_pg_net
      
volumes:
  resdb_volume:

networks:
  airflow_pg_net:
    external: true