config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

dbt_project:
  outputs:
    dev:
      type: postgres
      threads: 3
      host: pg_res
      port: 5432
      user: resdb
      pass: resdb
      dbname: resdb
      schema: stage
  target: dev
  